# Generated by Django 5.0 on 2023-12-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.URLField(default='https://via.placeholder.com/300'),
        ),
        migrations.AddField(
            model_name='course',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
