# Generated by Django 5.0 on 2023-12-09 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_course_duration_course_image_course_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='end_date',
        ),
    ]
