# Generated by Django 5.0 on 2023-12-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_course_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.URLField(blank=True, default='https://via.placeholder.com/300', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='workplace',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.URLField(blank=True, default='https://via.placeholder.com/300'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='workplace',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
